# Generated by Django 5.1.3 on 2024-11-19 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=100, verbose_name='ФИО')),
                ('phone', models.CharField(max_length=11, verbose_name='Номер')),
                ('email', models.CharField(max_length=100, verbose_name='Почта')),
                ('profession', models.CharField(max_length=65, verbose_name='Специальность')),
                ('experience', models.IntegerField(verbose_name='Стаж')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Изображение')),
                ('password', models.CharField(max_length=120, verbose_name='Пароль')),
            ],
        ),
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=100, verbose_name='ФИО')),
                ('phone', models.CharField(max_length=11, verbose_name='Номер телефона')),
                ('email', models.CharField(max_length=100, verbose_name='Почта')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Изображение')),
                ('password', models.CharField(max_length=120, verbose_name='Пароль')),
            ],
        ),
        migrations.CreateModel(
            name='Records',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35, verbose_name='Имя')),
                ('record', models.TextField(verbose_name='Отзыв')),
                ('date', models.CharField(max_length=25, verbose_name='Дата отзыва')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Изображение')),
            ],
        ),
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Дата и время приема')),
                ('description', models.TextField(blank=True, verbose_name='Описание проблемы')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='main.doctor', verbose_name='Врач')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='main.patients', verbose_name='Пациент')),
            ],
        ),
    ]
