# Generated by Django 5.1.3 on 2024-11-25 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=100, verbose_name='ФИО')),
                ('phone', models.CharField(max_length=11, verbose_name='Номер')),
                ('email', models.CharField(max_length=100, verbose_name='Почта')),
                ('profession', models.CharField(max_length=65, verbose_name='Специальность')),
                ('experience', models.IntegerField(verbose_name='Стаж')),
                ('room', models.CharField(max_length=50, verbose_name='Кабинет')),
                ('area', models.CharField(max_length=100, verbose_name='Район работы')),
                ('adress', models.CharField(max_length=120, verbose_name='Адрес кабинета')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Изображение профиля')),
                ('password', models.CharField(max_length=120, verbose_name='Пароль')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Описание новости')),
                ('date', models.CharField(max_length=30, verbose_name='Дата выпуска новости')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=100, verbose_name='ФИО')),
                ('phone', models.CharField(max_length=11, verbose_name='Номер телефона')),
                ('email', models.CharField(max_length=100, verbose_name='Почта')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Изображение профиля')),
                ('password', models.CharField(max_length=120, verbose_name='Пароль')),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35, verbose_name='Имя')),
                ('record', models.TextField(verbose_name='Отзыв')),
                ('date', models.CharField(max_length=25, verbose_name='Дата отзыва')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Изображение профиля')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Дата и время приема')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание проблемы')),
                ('recommendations', models.TextField(blank=True, null=True, verbose_name='Рекомендации')),
                ('visited', models.BooleanField(default=False, verbose_name='Посещенно')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='main.doctor', verbose_name='Врач')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='main.patient', verbose_name='Пациент')),
            ],
        ),
    ]
