# Generated by Django 5.1.3 on 2024-11-22 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Описание новости')),
                ('date', models.CharField(max_length=30, verbose_name='Дата выпуска новости')),
            ],
        ),
    ]
