# Generated by Django 5.1.3 on 2024-11-27 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='gender',
            field=models.CharField(choices=[('M', 'Мужчина'), ('F', 'Женщина')], default='M', max_length=1, verbose_name='Пол'),
        ),
        migrations.CreateModel(
            name='HomeVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=255, verbose_name='Имя пациента')),
                ('patient_phone', models.CharField(max_length=15, verbose_name='Контактный телефон')),
                ('address', models.TextField(verbose_name='Адрес вызова')),
                ('symptoms', models.TextField(blank=True, null=True, verbose_name='Симптомы')),
                ('requested_time', models.DateTimeField(auto_now_add=True, verbose_name='Время запроса')),
                ('scheduled_time', models.DateTimeField(blank=True, null=True, verbose_name='Запланированное время визита')),
                ('status', models.CharField(choices=[('PENDING', 'В ожидании'), ('ASSIGNED', 'Назначен врач'), ('COMPLETED', 'Завершено'), ('CANCELLED', 'Отменено')], default='PENDING', max_length=10, verbose_name='Статус')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_visits', to='main.doctor', verbose_name='Назначенный врач')),
            ],
            options={
                'verbose_name': 'Вызов врача на дом',
                'verbose_name_plural': 'Вызовы врачей на дом',
                'ordering': ['-requested_time'],
            },
        ),
    ]
