# Generated by Django 5.1.3 on 2024-12-11 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_doctor_area_alter_doctor_profession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='link',
        ),
    ]
