# Generated by Django 5.1.3 on 2024-11-27 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_doctor_gender_homevisit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homevisit',
            name='address',
            field=models.CharField(max_length=100, verbose_name='Адрес вызова'),
        ),
    ]
