# Generated by Django 5.1.3 on 2024-11-23 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_appointment_visited_alter_appointment_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='visited',
            field=models.BooleanField(verbose_name='Посещенно'),
        ),
    ]
