# Generated by Django 5.1.3 on 2024-11-27 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_homevisit_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата рабочего дня')),
                ('start_time', models.TimeField(default='08:00', verbose_name='Время начала работы')),
                ('end_time', models.TimeField(default='17:00', verbose_name='Время окончания работы')),
                ('break_start', models.TimeField(blank=True, null=True, verbose_name='Начало перерыва')),
                ('break_end', models.TimeField(blank=True, null=True, verbose_name='Конец перерыва')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='main.doctor', verbose_name='Врач')),
            ],
            options={
                'verbose_name': 'Расписание врача',
                'verbose_name_plural': 'Расписания врачей',
            },
        ),
    ]
