# Generated by Django 5.1.3 on 2024-11-27 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_doctorschedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorschedule',
            name='break_end',
            field=models.TimeField(blank=True, default='14:00', verbose_name='Конец перерыва'),
        ),
        migrations.AlterField(
            model_name='doctorschedule',
            name='break_start',
            field=models.TimeField(blank=True, default='13:00', verbose_name='Начало перерыва'),
        ),
        migrations.AlterField(
            model_name='doctorschedule',
            name='end_time',
            field=models.TimeField(default='20:00', verbose_name='Время окончания работы'),
        ),
    ]
