# Generated by Django 5.1.3 on 2024-11-25 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_appointment_visited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='visited',
            field=models.BooleanField(default=False, verbose_name='Посещенно'),
        ),
    ]
